name: Exercice 2

on:
  workflow_dispatch:

env:
  a: 1
  b: 3

jobs:
  job1:
    runs-on: ubuntu-latest

  steps:
  - name: print a et b
    if: ${{env.a > 0 && env.b > 0}} 
    run: |
      echo ${{ env.a }}
      echo ${{ env.b }}

  job2:
    needs: job1
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: |
        python script.py